name: "Docker"

on:
  workflow_call:
    inputs:
      dockerfile:
        description: The path of the Dockerfile to build.
        type: string
        required: true
      registry:
        description: The docker registry to log in to
        type: string
      context:
        description: The path of the docker build context. Defaults to '.'
        type: string
        default: '.'
      build-args:
        description: The build args to use in docker
        type: string
      platforms:
        description: The platforms to build the docker image for. This is a comma-separated list
        type: string
        default: linux/amd64
      tags:
        description: The comma-separated list of tags to use when pushing the docker image. Giving this a value will trigger a docker push.
        type: string
      version-info-file:
        description: 'The optional path of the VersionInfo files'
        type: string
        default: ''
    secrets:
      DOCKER_USERNAME:
        description: The Docker username to use for pushing the docker image
        required: false
      DOCKER_PASSWORD:
        description: The Docker username to use for pushing the docker image
        required: false

   
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-qemu-action@v1
    - uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      if: secrets.DOCKER_USERNAME != '' && secrets.DOCKER_PASSWORD != ''
      with:
        registry: ${{ inputs.registry }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Update VersionInfo
      if: inputs.version-info-file != ''
      uses: dolittle/update-version-info-action@v1
      with:
        version: ${{ needs.setup.outputs.next-version || '0.0.0-prerelease' }}
        files-to-update: ${{ inputs.version-info-file }}}
    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        push: false
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        build-args: ${{ inputs.build-args }}
        platforms: ${{ inputs.platforms }}
    - name: Push Docker image
      if: inputs.tags != ''
      uses: docker/build-push-action@v2
      with:
        push: true
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        build-args: ${{ inputs.build-args }}
        platforms: ${{ inputs.platforms }}
        tags: ${{ inputs.tags }}
